name: arlens
description: AR Lens Calculator & Senfrost Aircon Services App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Supabase
  supabase_flutter: ^2.5.6

  # Navigation
  go_router: ^14.2.0

  # UI & Utils
  flutter_screenutil: ^5.9.0
  intl: ^0.19.0
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  
  # Image & Camera
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  
  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
#    - assets/icons/